### ISSUE TITLE
test/tntnet-test fails on arm platform

### ISSUE THREAD

**Issue by martinkg** [maekitalo/tntnet#45]
i tried again compilation with your changes.
test/tntnet-test fails on arm platform see logs of the fedora build server: https://kojipkgs.fedoraproject.org//work/tasks/9563/10369563/build.log

**Comment by maekitalo** [comment]
I have currently no idea, what is going wrong here. It looks like the segfault happens in component::testArg. There are no changes there.

**Comment by martinkg** [comment]
Will no longer occur.
