### ISSUE TITLE
config.h isn't installed

### ISSUE THREAD

**Issue by jplatte** [maekitalo/tntnet#46]
The (generated) file `config.h` currently isn't installed as part of the tntnet library, but is included in several headers: `ssl.h`, `listener.h`, `pollerimpl.h`, and on my fork's v3.0 branch `tntconfig.h`as well (that's how I found out). I would suggest moving it from `framework/common` to `framework/common/tnt`.

If you think it shouldn't be installed, IMHO the headers including it shouldn't be installed either, and moved from `framework/common/tnt` to `framework/common` (and from _HEADERS to _SOURCES).

I will fix this on my fork and include it in the v3.0 branch. [Here](https://github.com/jplatte/tntnet/commit/fd8aef4869bf60538ccf30c0f463ab232ffc3789#diff-20f87b1f709469ca86b536d4ac13be68R461) is what I use `config.h` for in `tntconfig.h`.

By the way, I would be happy discussion this and the other changes on there with you on IRC, or maybe [gitter.im](https://gitter.im/)? It's pretty similar to IRC (in fact it allows connecting to it via IRC) but has a log / history so users don't have to be online simultaneously or use a bouncer.

**Comment by aggsol** [comment]
You can use the mailinglist https://lists.sourceforge.net/lists/listinfo/tntnet-general
or try IRC #tntnet at irc.freenode.net

**Comment by maekitalo** [comment]
The config.h must not be installed. It is never installed.

And yes - the headers, which need config.h must not be installed and are not installed. You should not include config.h in public headers.

**Comment by jplatte** [comment]
Okay, what would be the problem with installing `config.h`?

I didn't realize before that the headers including it aren't installed, I thought all the headers in the `tnt` subdirectory were installed.
