### ISSUE TITLE
Standalone tntnet-project templates require libtool

### ISSUE THREAD

**Issue by jplatte** [maekitalo/tntnet#47]
libtool is only needed when building libraries and including it (through `LT_INIT`) adds an additional build dependency as well as resulting in a bigger configure script that checks for things that aren't used.

I'll create a PR for this soon, just don't release tntnet 2.3 yet, please :)

**Comment by maekitalo** [comment]
I just removed it from the standalone project templates.

**Comment by jplatte** [comment]
Alright, thanks :)
